export const reactorWorkedExample = {
  cstr: {
    inputType: "volume_and_kinetics",
    conversion: "",
    volume: "3.0",
    rateConstant: "0.01",
    recyclingRatio: "0",
    initialTemperature: "300",
    initialPressure: "101325",
    finalTemperature: "450",
    finalPressure: "101325",
    components: [
      {
        state: "liquid",
        component_name: "Water",
        flow_rate_inlet: "1.2",
        molar_concentration_inlet: "5000",
      },
      {
        state: "liquid",
        component_name: "Ethanol",
        flow_rate_inlet: "0",
        molar_concentration_inlet: "0",
      },
    ],
    stoichiometricCoefficients: ["-1", "1"],
    reactionOrders: ["1", "0.5"],
  },
  pfr: {
    inputType: "volume_and_kinetics",
    conversion: "",
    volume: "3.0",
    rateConstant: "0.01",
    recyclingRatio: "0",
    initialTemperature: "300",
    initialPressure: "101325",
    finalTemperature: "450",
    finalPressure: "101325",
    components: [
      {
        state: "liquid",
        component_name: "Water",
        flow_rate_inlet: "1.2",
        molar_concentration_inlet: "5000",
      },
      {
        state: "liquid",
        component_name: "Ethanol",
        flow_rate_inlet: "0",
        molar_concentration_inlet: "0",
      },
    ],
    stoichiometricCoefficients: ["-1", "1"],
    reactionOrders: ["1", "0.5"],
  },
  plot: {
    rateConstant: "0.3",
    maxConversion: "0.6",
    activationEnergy: "55000",
    referenceTemperature: "300",
  },
} as const;
