import type { ModuleExploratoryConfig } from "@/features/exploratory/types";

export const sizingExploratory: ModuleExploratoryConfig = {
  module: "sizing",
  templates: [
    {
      key: "process-line",
      name: "Linha de processo - Água, v=1,5 m/s",
      fields: { "flow-rate": "0.01", velocity: "1.5" },
      sliders: [
        {
          id: "sizing-sl-flow",
          field: "flow-rate",
          label: "Vazao",
          unit: "m3/s",
          min: 0.001,
          max: 0.05,
          step: 0.001,
          default: 0.01,
        },
        {
          id: "sizing-sl-vel",
          field: "velocity",
          label: "Velocidade",
          unit: "m/s",
          min: 0.5,
          max: 3,
          step: 0.1,
          default: 1.5,
        },
      ],
      steps: [
        "Observe o diametro teorico calculado e a selecao do diametro real para o caso base.",
        "Aumente a vazao e note o crescimento do diametro necessario para manter a mesma velocidade.",
        "Reduza a velocidade para discutir linhas de succao e o aumento do DN comercial.",
        "Salve os cenarios e compare o compromisso entre custo de tubulacao e perda de carga.",
      ],
      activity:
        "Qual e a maior vazao que ainda permite um DN comercial abaixo de 100 mm neste caso?",
    },
    {
      key: "suction-line",
      name: "Linha de sucção - Água, v=0,8 m/s",
      fields: { "flow-rate": "0.005", velocity: "0.8" },
      sliders: [
        {
          id: "sizing-sl-flow",
          field: "flow-rate",
          label: "Vazao",
          unit: "m3/s",
          min: 0.001,
          max: 0.03,
          step: 0.001,
          default: 0.005,
        },
        {
          id: "sizing-sl-vel",
          field: "velocity",
          label: "Velocidade",
          unit: "m/s",
          min: 0.5,
          max: 2,
          step: 0.1,
          default: 0.8,
        },
      ],
      steps: [
        "Use o caso de succao para trabalhar velocidades menores e maior diametro nominal.",
        "Aumente a velocidade e compare o ganho de compacidade com o risco hidraulico associado.",
        "Observe como o campo de diametro calculado alimenta a selecao do diametro real.",
        "Salve dois cenarios e compare os DNs sugeridos.",
      ],
      activity:
        "Em qual faixa de velocidade a linha ainda se mantem coerente para succao de bomba?",
    },
  ],
};

export const flowExploratory: ModuleExploratoryConfig = {
  module: "flow",
  templates: [
    {
      key: "water-pvc-dn100",
      name: "Água a 20°C — PVC DN100, v=1,5 m/s",
      fields: {
        "characteristic-diameter": "100",
        "reynolds-velocity": "1.5",
        density: "998",
        "dynamic-viscosity": "0.001",
      },
      sliders: [
        {
          id: "flow-sl-vel",
          field: "reynolds-velocity",
          label: "Velocidade",
          unit: "m/s",
          min: 0.02,
          max: 5,
          step: 0.01,
          default: 1.5,
        },
        {
          id: "flow-sl-diam",
          field: "characteristic-diameter",
          label: "Diametro",
          unit: "mm",
          min: 50,
          max: 300,
          step: 10,
          default: 100,
        },
      ],
      steps: [
        "Observe o numero de Reynolds e localize o ponto operacional no Diagrama de Moody.",
        "Reduza a velocidade para aproximar o sistema do regime laminar e acompanhe a mudanca no fator de atrito.",
        "Varie o diametro para perceber o efeito da rugosidade relativa no ponto operacional.",
        "Salve cenarios distintos e compare os pontos sobrepostos no grafico.",
      ],
      activity: "Qual velocidade leva este sistema para a fronteira laminar em DN100?",
      meta: { roughness: 0.0015 },
    },
    {
      key: "oil-steel-dn80",
      name: "Óleo viscoso — Aço DN80, v=0,5 m/s",
      fields: {
        "characteristic-diameter": "80",
        "reynolds-velocity": "0.5",
        density: "870",
        "dynamic-viscosity": "0.05",
      },
      sliders: [
        {
          id: "flow-sl-vel",
          field: "reynolds-velocity",
          label: "Velocidade",
          unit: "m/s",
          min: 0.1,
          max: 3,
          step: 0.1,
          default: 0.5,
        },
        {
          id: "flow-sl-diam",
          field: "characteristic-diameter",
          label: "Diametro",
          unit: "mm",
          min: 50,
          max: 200,
          step: 10,
          default: 80,
        },
      ],
      steps: [
        "Compare o escoamento viscoso com o caso de agua e veja como a viscosidade domina o Reynolds.",
        "Aumente a velocidade para se aproximar da transicao de regime.",
        "Use o diametro como variavel de comparacao para alterar a rugosidade relativa do ponto no Moody.",
        "Salve e compare com o template de agua.",
      ],
      activity: "Qual velocidade minima produz turbulencia neste caso de oleo?",
      meta: { roughness: 0.045 },
    },
    {
      key: "air-duct-200",
      name: "Ar — Duto 200 mm, v=3 m/s",
      fields: {
        "characteristic-diameter": "200",
        "reynolds-velocity": "3",
        density: "1.2",
        "dynamic-viscosity": "0.0000181",
      },
      sliders: [
        {
          id: "flow-sl-vel",
          field: "reynolds-velocity",
          label: "Velocidade",
          unit: "m/s",
          min: 0.2,
          max: 10,
          step: 0.2,
          default: 3,
        },
        {
          id: "flow-sl-diam",
          field: "characteristic-diameter",
          label: "Diametro hidraulico",
          unit: "mm",
          min: 100,
          max: 500,
          step: 25,
          default: 200,
        },
      ],
      steps: [
        "Observe como a combinacao de baixa densidade e baixa viscosidade desloca o ponto do ar no diagrama.",
        "Leve o sistema para a zona de transicao reduzindo a velocidade.",
        "Aumente a velocidade para notar a menor sensibilidade do fator de atrito em regime muito turbulento.",
        "Salve e compare os tres fluidos estudados.",
      ],
      activity: "Que diametro minimo manteria a velocidade de ventilacao abaixo de 8 m/s?",
      meta: { roughness: 0.09 },
    },
  ],
};

export const pumpExploratory: ModuleExploratoryConfig = {
  module: "pump",
  templates: [
    {
      key: "standard-pump",
      name: "Bombeamento padrão — água, L=100 m, DN100",
      fields: {
        "pipe-length": "100",
        "headloss-diameter": "100",
        "headloss-flow-rate": "0.01",
        "headloss-friction-factor": "0.02",
        "headloss-velocity": "1.27",
        "atmospheric-pressure": "1.033",
        "vapor-pressure": "0.023",
        "specific-mass": "998",
        "npsh-friction-factor": "2",
        "pump-inlet-velocity": "1.27",
        "gauge-elevation": "3",
        pressure1: "0",
        pressure2: "200000",
        elevation1: "0",
        elevation2: "5",
        velocity1: "1.27",
        velocity2: "1.27",
        "head-specific-mass": "998",
        "head-friction-factor": "2",
        "npsh-required": "3",
      },
      sliders: [
        {
          id: "pump-sl-len",
          field: "pipe-length",
          label: "Comprimento",
          unit: "m",
          min: 20,
          max: 300,
          step: 10,
          default: 100,
        },
        {
          id: "pump-sl-flow",
          field: "headloss-flow-rate",
          label: "Vazao",
          unit: "m3/s",
          min: 0.005,
          max: 0.03,
          step: 0.001,
          default: 0.01,
        },
        {
          id: "pump-sl-elev",
          field: "gauge-elevation",
          label: "Cota de succao",
          unit: "m",
          min: 0,
          max: 10,
          step: 0.5,
          default: 3,
        },
      ],
      steps: [
        "Observe a curva de perda de carga para o caso base com agua.",
        "Aumente o comprimento para ver a curva se deslocar e a perda de carga crescer.",
        "Altere a cota de succao para enxergar o impacto direto na margem de NPSH.",
        "Salve cenarios e compare a decomposicao da altura manometrica.",
      ],
      activity: "Qual vazao aproxima o sistema do limite de cavitacao neste arranjo?",
    },
    {
      key: "high-resistance",
      name: "Alta resistência — óleo, L=200 m, DN80",
      fields: {
        "pipe-length": "200",
        "headloss-diameter": "80",
        "headloss-flow-rate": "0.008",
        "headloss-friction-factor": "0.035",
        "headloss-velocity": "1.59",
        "atmospheric-pressure": "1.033",
        "vapor-pressure": "0.001",
        "specific-mass": "870",
        "npsh-friction-factor": "5",
        "pump-inlet-velocity": "1.59",
        "gauge-elevation": "2",
        pressure1: "0",
        pressure2: "300000",
        elevation1: "0",
        elevation2: "8",
        velocity1: "1.59",
        velocity2: "1.59",
        "head-specific-mass": "870",
        "head-friction-factor": "5",
        "npsh-required": "3",
      },
      sliders: [
        {
          id: "pump-sl-len",
          field: "pipe-length",
          label: "Comprimento",
          unit: "m",
          min: 50,
          max: 400,
          step: 25,
          default: 200,
        },
        {
          id: "pump-sl-flow",
          field: "headloss-flow-rate",
          label: "Vazao",
          unit: "m3/s",
          min: 0.002,
          max: 0.02,
          step: 0.001,
          default: 0.008,
        },
        {
          id: "pump-sl-elev",
          field: "gauge-elevation",
          label: "Cota de succao",
          unit: "m",
          min: 0,
          max: 8,
          step: 0.5,
          default: 2,
        },
      ],
      steps: [
        "Observe a penalizacao hidraulica do oleo em uma linha mais resistente.",
        "Reduza a vazao para comparar como a perda de carga cai mais rapidamente.",
        "Compare a margem de NPSH com o caso de agua.",
        "Salve e compare os dois cenarios principais de operacao.",
      ],
      activity:
        "Que diametro seria necessario para reduzir hf sem alterar a vazao de projeto?",
    },
  ],
};

export const reactorExploratory: ModuleExploratoryConfig = {
  module: "reactor",
  templates: [
    {
      key: "first-order",
      name: "Reação de 1a ordem - A para B",
      fields: {
        "cstr-conversion": "0.8",
        "cstr-rate-constant": "0.5",
        "pfr-conversion": "0.8",
        "pfr-rate-constant": "0.5",
        "plot-rate-constant": "0.5",
        "plot-max-conversion": "0.95",
      },
      sliders: [
        {
          id: "reactor-sl-conv",
          field: "cstr-conversion",
          linkedFields: ["pfr-conversion"],
          extraFields: ["plot-max-conversion"],
          label: "Conversao X",
          unit: "",
          min: 0.1,
          max: 0.95,
          step: 0.01,
          default: 0.8,
        },
        {
          id: "reactor-sl-k",
          field: "cstr-rate-constant",
          linkedFields: ["pfr-rate-constant"],
          extraFields: ["plot-rate-constant"],
          label: "Constante k",
          unit: "min-1",
          min: 0.05,
          max: 2,
          step: 0.05,
          default: 0.5,
        },
      ],
      steps: [
        "Use o template para comparar a eficiencia volumetrica de CSTR e PFR no diagrama de Levenspiel.",
        "Aumente a conversao e note como o CSTR cresce mais rapidamente do que o PFR.",
        "Aumente a constante cinetica para reduzir ambos os volumes sem alterar a tendencia relativa.",
        "Salve cenarios e sobreponha as curvas de volume no grafico.",
      ],
      activity:
        "Em que faixa de conversao a diferenca relativa entre CSTR e PFR se torna mais visivel?",
    },
    {
      key: "second-order",
      name: "Reação de 2a ordem - A para B",
      fields: {
        "cstr-conversion": "0.6",
        "cstr-rate-constant": "0.1",
        "pfr-conversion": "0.6",
        "pfr-rate-constant": "0.1",
        "plot-rate-constant": "0.1",
        "plot-max-conversion": "0.85",
      },
      sliders: [
        {
          id: "reactor-sl-conv",
          field: "cstr-conversion",
          linkedFields: ["pfr-conversion"],
          extraFields: ["plot-max-conversion"],
          label: "Conversao X",
          unit: "",
          min: 0.1,
          max: 0.9,
          step: 0.01,
          default: 0.6,
        },
        {
          id: "reactor-sl-k",
          field: "cstr-rate-constant",
          linkedFields: ["pfr-rate-constant"],
          extraFields: ["plot-rate-constant"],
          label: "Constante k",
          unit: "L mol-1 min-1",
          min: 0.05,
          max: 1,
          step: 0.05,
          default: 0.1,
        },
      ],
      steps: [
        "Compare um caso de segunda ordem com a referencia de primeira ordem no grafico de volume.",
        "Aumente a conversao e observe como o crescimento de volume se torna mais severo.",
        "Varie k para discutir o efeito combinado de cinetica mais lenta e conversao elevada.",
        "Salve cenarios e compare as curvas sobrepostas.",
      ],
      activity:
        "Como a ordem da reacao altera a distancia entre as curvas de CSTR e PFR?",
      meta: { reactionOrders: [2, 0] },
    },
  ],
};

export const balanceExploratory: ModuleExploratoryConfig = {
  module: "balance",
  templates: [
    {
      key: "simple-separation",
      name: "Separação simples - alimentação de 100 mol/h",
      fields: {
        "split-fraction": "0.5",
        "feed-main-fraction": "0.6",
      },
      sliders: [
        {
          id: "balance-sl-recycle",
          field: "split-fraction",
          label: "Razao de reciclo",
          unit: "",
          min: 0,
          max: 0.9,
          step: 0.05,
          default: 0.5,
        },
        {
          id: "balance-sl-feed",
          field: "feed-main-fraction",
          label: "Fracao do componente principal",
          unit: "",
          min: 0.1,
          max: 0.9,
          step: 0.05,
          default: 0.6,
        },
      ],
      steps: [
        "Carregue o exemplo do modulo e calcule o balanco para conferir o fechamento global.",
        "Gere o grafico de correntes e compare entradas e saidas por corrente.",
        "Ajuste manualmente as correntes do exemplo e recalcule.",
        "Discuta com a turma como a conservacao de massa aparece no conjunto de resultados.",
      ],
      activity: "Que mudancas nas correntes de saida mantem o fechamento do balanco?",
    },
    {
      key: "recycle-system",
      name: "Sistema com reciclo - razão de reciclo 50%",
      fields: {
        "split-fraction": "0.5",
        "feed-main-fraction": "0.5",
      },
      sliders: [
        {
          id: "balance-sl-recycle",
          field: "split-fraction",
          label: "Razao de reciclo",
          unit: "",
          min: 0.1,
          max: 0.9,
          step: 0.05,
          default: 0.5,
        },
        {
          id: "balance-sl-feed",
          field: "feed-main-fraction",
          label: "Fracao do componente principal",
          unit: "",
          min: 0.1,
          max: 0.9,
          step: 0.05,
          default: 0.5,
        },
      ],
      steps: [
        "Carregue o exemplo e concentre a discussao no efeito do reciclo sobre as correntes internas.",
        "Use o slider de reciclo para ampliar ou reduzir a parcela retornada ao processo.",
        "Altere a fracao do componente principal na alimentacao e compare o grafico de correntes.",
        "Salve cenarios e discuta a sensibilidade do fechamento ao reciclo.",
      ],
      activity:
        "Em que faixa de reciclo o sistema passa a depender mais das correntes internas do que da alimentacao fresca?",
    },
  ],
};
