import type { ModuleExploratoryConfig } from "@/features/exploratory/types";

export const componentsExploratory: ModuleExploratoryConfig = {
  module: "components",
  templates: [
    {
      key: "equilibrium-workbench",
      name: "Workbench termodinâmico",
      fields: {
        "surface-fluid": "Water",
        "surface-property": "D",
        "surface-temperature-min": "300",
        "surface-temperature-max": "400",
        "surface-pressure-min": "101325",
        "surface-pressure-max": "500000",
        "binary-fluid-1": "Water",
        "binary-fluid-2": "Ethanol",
        "binary-vle-pressure": "101325",
        "binary-vle-samples": "21",
        "mccabe-distillate": "0.95",
        "mccabe-bottoms": "0.05",
        "mccabe-feed": "0.5",
        "mccabe-reflux": "2.5",
        "mccabe-q": "1",
        "mccabe-max-stages": "10",
      },
      sliders: [
        {
          id: "components-sl-binary-pressure",
          field: "binary-vle-pressure",
          label: "Pressão VLE",
          unit: "Pa",
          min: 50000,
          max: 200000,
          step: 1000,
          default: 101325,
        },
        {
          id: "components-sl-reflux",
          field: "mccabe-reflux",
          label: "Refluxo",
          unit: "-",
          min: 0.5,
          max: 6,
          step: 0.1,
          default: 2.5,
        },
        {
          id: "components-sl-q",
          field: "mccabe-q",
          label: "q",
          unit: "-",
          min: 0,
          max: 2,
          step: 0.05,
          default: 1,
        },
        {
          id: "components-sl-surface-pmax",
          field: "surface-pressure-max",
          label: "P máx. superfície",
          unit: "Pa",
          min: 200000,
          max: 2000000,
          step: 100000,
          default: 500000,
        },
      ],
      steps: [
        "Use o template para carregar um caso binário base de equilíbrio líquido-vapor.",
        "Varie a pressão do VLE para observar como o T-x-y muda e como isso afeta o McCabe-Thiele.",
        "Ajuste o refluxo e a q-line para enxergar a troca entre retas de operação e estágios teóricos.",
        "Mude a faixa de pressão da superfície de propriedades e veja como a densidade responde ao domínio termodinâmico.",
      ],
      activity:
        "Qual combinação de pressão e refluxo reduz o número de estágios teóricos sem sair da faixa física do equilíbrio binário?",
    },
  ],
};
