export const pumpWorkedExample = {
  headloss: {
    method: "Darcy-Weisbach",
    pipeLength: "100",
    diameter: "100",
    flowRate: "0.01",
    velocity: "1.27",
    frictionFactor: "0.02",
    roughnessCoefficient: "140",
    reynolds: "127000",
    frictionMethod: "SwameeJain",
    composition: "PVC",
  },
  npsh: {
    manometricPressure: "0",
    atmosphericPressure: "1.033",
    vaporPressure: "0.023",
    density: "998",
    frictionFactor: "2",
    pumpInletVelocity: "1.27",
    gaugeElevation: "3",
    required: "3",
  },
  head: {
    pressure1: "0",
    pressure2: "200000",
    elevation1: "0",
    elevation2: "5",
    velocity1: "1.27",
    velocity2: "1.27",
    density: "998",
    frictionFactor: "2",
  },
} as const;
